name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g. v1.0.0)'
        required: true
        default: 'v1.0.0'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'

      - name: Build linux amd64
        run: GOOS=linux GOARCH=amd64 go build -o dist/gmfi-linux-amd .

      - name: Build linux arm64
        run: GOOS=linux GOARCH=arm64 go build -o dist/gmfi-linux-arm .

      - name: Build macos arm64
        run: GOOS=darwin GOARCH=arm64 go build -o dist/gmfi-macos-arm .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: "Release ${{ github.event.inputs.version }}"
          files: |
            dist/gmfi-linux-amd
            dist/gmfi-linux-arm
            dist/gmfi-macos-arm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
